add_requires('eigen')
add_requires('coost')
add_requires('spdlog', {configs={fmt_external = true}})
add_requires("doctest", {})

target("acg_core")
  set_kind('static')
  add_includedirs('include', {public = true})
  add_files('src/**.cpp')
  add_packages('eigen', 'coost', 'spdlog', {public = true})
target_end()

target('acg_core_test')
  add_files('test/**.cpp')
  add_packages('doctest')
  add_deps('acg_core')
target_end()
