target('acg_port')
  set_kind('static')
  set_group('library')
  add_includedirs('include', { public = true })
  add_files('source/**.cpp')
  add_deps('acg_core', {public = true})
target_end()

target('acg_port_test')
  set_kind('binary')
  set_group('test')
  add_files('test/**.cpp')
  add_deps('acg_port')
  add_packages('doctest')
target_end()
