name: cpp-build
on: [push]


jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: install Vulkan
        run: |
          mkdir -p $HOME/Downloads
          mkdir -p $HOME/tools
          cd $HOME && ls
          wget -q -P $HOME/Downloads https://sdk.lunarg.com/sdk/download/1.3.236.0/linux/vulkansdk-linux-x86_64-1.3.236.0.tar.gz
          tar xf $HOME/Downloads/vulkansdk-linux-x86_64-1.3.236.0.tar.gz --directory=$HOME/tools/
          source $HOME/tools/1.3.236.0/setup-env.sh
      - uses: actions/checkout@v3
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: '2.7.5'
          actions-cache-folder: '.xmake-cache'
      - name: configure
        run: |
          cd ${{ github.workspace }}
          source $HOME/tools/1.3.236.0/setup-env.sh
          xmake f -y --toolchain=clang -m debug
      - name: build
        run: | 
          source $HOME/tools/1.3.236.0/setup-env.sh
          xmake b -v
      - name: run-test
        run: xmake run --group=test
