name: cpp-build
on: [push]


jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: install Vulkan
        run: |
          sudo apt update
          # sudo apt install libglm-dev cmake libxcb-dri3-0 libxcb-present0 libpciaccess0 libpng-dev libxcb-keysyms1-dev libxcb-dri3-dev libx11-dev g++ gcc g++-multilib libmirclient-dev libwayland-dev libxrandr-dev libxcb-randr0-dev libxcb-ewmh-dev git python python3 bison libx11-xcb-dev liblz4-dev libzstd-dev python3-distutils ocaml-core ninja-build pkg-config libxml2-dev wayland-protocols python3-jsonschema
          # sudo apt install qtbase5-dev
          wget -P $Home/Downloads https://sdk.lunarg.com/sdk/download/1.3.236.0/linux/vulkansdk-linux-x86_64-1.3.236.0.tar.gz
          tar xf $HOME/Downloads/vulkansdk-linux-x86_64-1.3.236.0.tar.gz --directory=$HOME/tools/
          source $HOME/tools/1.3.236.0/setup-env.sh
      - uses: actions/checkout@v3
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: '2.7.5'
          actions-cache-folder: '.xmake-cache'
      - name: configure
        run: |
          cd ${{ github.workspace }}
          source $HOME/tools/1.3.236.0/setup-env.sh
          xmake f -y --toolchain=clang -m debug
      - name: build
        run: | 
          source $HOME/tools/1.3.236.0/setup-env.sh
          xmake b -v
      - name: run-test
        run: xmake run --group=test
